from __future__ import annotations

from dataclasses import dataclass


@dataclass(slots=True)
class NodeEvent:
    """
    Event generated by a network node.
    """

    event_type: str
    node_id: str
    timestamp: int
    details: dict[str, str]
